---
title: "CSE280A_project"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(data.table)
library(tidyr)
library(stringr)
library(data.table)
library("biomaRt")
library(purrr)
library(fuzzyjoin)
library(ggplot2)
library(plyr)
```

```{r}
oncogenes = read.table("Oncogene list_ONGene.txt",sep="\t",header=T,quote = "")
structures = read.table(file = "~/Desktop/Project/CCLE/AC_default/ccle_amplicon_classification_profiles.tsv", header = T, sep = "\t")
cyclic = structures %>% filter(amplicon_decomposition_class == "Cyclic")
cyclic$sample_name = as.character(cyclic$sample_name)
cyclic$amplicon_number = as.character(cyclic$amplicon_number)
cyclic = cyclic %>% mutate(bedname = paste(paste(sample_name, amplicon_number, sep = "_"), amplicon_number,sep = "_"))
```

```{r}
files <- data.frame(list.files(path="~/Desktop/Project/CCLE/AC_default/classification_bed_files", pattern="*.bed", full.names=TRUE, recursive=FALSE))
colnames(files) = "file"
cyclic_files = grep(paste(cyclic$bedname,collapse="|"), 
                        files$file, value=TRUE)

beds = lapply(cyclic_files, function(x) {
  bed <- as.data.frame(read.table(x,header = FALSE, sep="\t",stringsAsFactors=FALSE, quote="", col.names = c("chromosome","start","end")))
      bed$tissue = gsub("/Users/heliz/Desktop/Project/CCLE/AC_default/classification_bed_files/","",x)
  return(bed)
})
data = as.data.frame(do.call(rbind, beds))
data = data %>% mutate(tissue_type = strsplit(data$tissue,"_")%>% map_chr(., 2))
head(data,10)

```

more Data
```{r}
structures2 = read.table(file = "~/Desktop/Project/PancancerECDNACellLine_classification_results_122320/PancancerECDNA_samplefiles_amplicon_classification_profiles.tsv", header = T, sep = "\t")
Cyclic2 = structures2 %>% filter(amplicon_decomposition_class == "Cyclic")
Cyclic2 = Cyclic2 %>%  mutate(gene = strsplit(sample_name,"_") %>% map_chr(.,2)) %>% filter(gene %in% oncogenes$OncogeneName) %>% mutate(cell_line = strsplit(sample_name,"_") %>% map_chr(.,1))
Cyclic2$bedname = paste(Cyclic2$sample_name,Cyclic2$amplicon_number,sep = "_")


```

New bed files
```{r}
files2 <- data.frame(list.files(path="~/Desktop/Project/PancancerECDNACellLine_classification_results_122320/classification_bed_files", pattern="*.bed", full.names=TRUE, recursive=FALSE))
colnames(files2) = "file"
cyclic_files2 = grep(paste(Cyclic2$bedname,collapse="|"), 
                        files2$file, value=TRUE)

beds2 = lapply(cyclic_files2, function(x) {
  bed <- as.data.frame(read.table(x,header = FALSE, sep="\t",stringsAsFactors=FALSE, quote="", col.names = c("chromosome","start","end")))
  bed$cell_line =  strsplit(gsub("/Users/heliz/Desktop/Project/PancancerECDNACellLine_classification_results_122320/classification_bed_files/","",x),'_') %>% map_chr(.,1)
  return(bed)
})

data2 = as.data.frame(do.call(rbind, beds2))
head(data2,10)
```

Tissue type for new dataset
```{r}
cell_lines = data.frame(unique(Cyclic2$cell_line))
colnames(cell_lines) = "cell_line"
cell_lines$tissue_type = cell_lines$Cell_line
cell_lines$tissue_type[1] = "BREAST"
cell_lines$tissue_type[5] = "LUNG"
cell_lines$tissue_type[6] = "BREAST"
cell_lines$tissue_type[7] = "LUNG"
cell_lines$tissue_type[23] = "COLON"
cell_lines$tissue_type[22] = "OVARY"
cell_lines$tissue_type[21] = "PROSTATE"
cell_lines$tissue_type[20] = "BREAST"
cell_lines$tissue_type[17] = "BLOOD"
cell_lines$tissue_type[19] = "MEDULLOBLASTOMA"
cell_lines$tissue_type[15] = "GLIOBLASTOMA"
cell_lines$tissue_type[3] = "GLIOBLASTOMA"
cell_lines$tissue_type[4] = "GLIOBLASTOMA"
cell_lines$tissue_type[8] = "GLIOBLASTOMA"
cell_lines$tissue_type[11] = "GLIOBLASTOMA"
cell_lines$tissue_type[10] = "GLIOBLASTOMA"
cell_lines$tissue_type[12] = "GLIOBLASTOMA"
cell_lines$tissue_type[9] = "GLIOBLASTOMA"
cell_lines$tissue_type[13] = "GLIOBLASTOMA"
cell_lines$tissue_type[14] = "GLIOBLASTOMA"
cell_lines$tissue_type[16] = "GLIOBLASTOMA"
cell_lines$tissue_type[18] = "MEDULLOBLASTOMA"
cell_lines$tissue_type[2] = "GLIOBLASTOMA"

write.table(cell_lines,"cell_line_tissue.tsv",row.names = F,sep = '\t')

data2 = merge(data2,cell_lines,by = "cell_line")

```

joining two datasets
```{r}
data = rbind(data %>% dplyr::select(chromosome,start,end,tissue_type), data2 %>% dplyr::select(chromosome,start,end,tissue_type))
```


```{r}

listMarts(host="www.ensembl.org")
ensembl = useMart(biomart = "ENSEMBL_MART_ENSEMBL",dataset="hsapiens_gene_ensembl")
filters = listFilters(ensembl)

```

Getting oncogene locations and forming empty oncogene-tissue type
```{r}
oncogene_ids=getBM(attributes = c("hgnc_symbol","ensembl_gene_id","start_position", "end_position","chromosome_name"),filters = c("hgnc_symbol"),values = unlist(as.list(oncogenes$OncogeneName)), mart = ensembl)

added = data.frame(matrix(0, nrow = nrow(oncogene_ids), ncol = length(unique(data$tissue_type))))
colnames(added) = unique(data$tissue_type)

oncogene_ids = cbind(oncogene_ids,added)
oncogene_ids$length = oncogene_ids$end_position - oncogene_ids$start_position
oncogene_ids$chromosome_name = paste("chr",oncogene_ids$chromosome_name,sep = "")


```


Saving intervals for each Oncogene
```{r}
ecDNA_loc = vector(mode="list", length=length(oncogene_ids$hgnc_symbol))
names(ecDNA_loc) = oncogene_ids$hgnc_symbol
```

Filling Oncogene-Tissue_type Table
```{r}
for (j in 1:nrow(oncogene_ids)){
  for (i in 1:nrow(data)){
    if ((oncogene_ids[j,'start_position'] >= (data[i,'start'] - oncogene_ids[j,'length']/3)) && (oncogene_ids[j,'end_position'] <= (data[i,'end'] + oncogene_ids[j,'length']/3)) && 
        oncogene_ids[j,'chromosome_name']  == data[i,"chromosome"]){
      oncogene_ids[j,data[i,'tissue_type']] <-  (oncogene_ids[j,data[i,'tissue_type']] + 1)
      ecDNA_loc[oncogene_ids[j,'hgnc_symbol']][[1]] = append(ecDNA_loc[oncogene_ids[j,'hgnc_symbol']][[1]],rbind(data[i,'start'], data[i,'end']))
    }
  }
}
```

```{r}
head(oncogene_ids,20)
write.csv(oncogene_ids,"oncogene_tissue_type.csv",row.names = F)
write.csv(data,"data.csv",row.names = F)

```

Sum rows 
```{r}
sum_happened = oncogene_ids %>% mutate(sum = rowSums(oncogene_ids[,6:29]))
sum_happened = sum_happened %>% arrange(desc(sum))
```


Distribution of files
```{r}
files_df = data.frame(files)
tissue_types = data.frame(unique(data$tissue_type))
colnames(tissue_types) = "Tissue"
files_df = files_df %>% regex_inner_join(tissue_types,by = c(file = "Tissue")) %>% group_by(Tissue) %>% dplyr::summarise(Files_n = n())

cyclic_files_df = data.frame(cyclic_files) 
colnames(cyclic_files_df) = "files"
cyclic_files_df = cyclic_files_df %>% regex_inner_join(tissue_types,by = c(files = "Tissue")) %>% group_by(Tissue) %>% dplyr::summarise(Cyclic_n = n())

all = inner_join(cyclic_files_df,files_df,by = c(Tissue = "Tissue"))

```

Plot distribution
```{r fig.height=5}

all.long = gather(all, variable,value, -Tissue)
ggplot(data = all.long, aes(x = Tissue, y = value, fill = variable)) +
  geom_col(position = position_dodge(),stat = "identity") + xlab("Tissue Type") + ylab("Number of files") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + geom_text(aes(label = value), position=position_dodge(width=0.9), vjust=-0.25)
ggsave("tissue_distribution.jpg")
```
compacting
```{r}
columns = c("hgnc_symbol",tissue_types$Tissue)
filtered_table = oncogene_ids[,columns] 
numbers = filtered_table[,2:25] %>% select_if(colSums(.) != 0)
numbers$hgnc_symbol = filtered_table$hgnc_symbol

oncogene_compact = numbers %>% mutate(n_total_oncogene = rowSums(numbers[,1:19])) %>% arrange(desc(n_total_oncogene)) %>% filter(n_total_oncogene >= 4)
write.csv(oncogene_compact,"compacted.csv",row.names = F)
write.csv(filtered_table,"filtered.csv",row.names = F)
write.table(all,"tissue_files.tsv",row.names = F)
```


##intervals
```{r}
top = sum_happened %>% filter(sum >= 4) %>% dplyr::select(hgnc_symbol)
top_intervals = ecDNA_loc[top$hgnc_symbol]
top_df = as.data.frame(as.matrix(top_intervals))
top_df2 = data.frame(lapply(top_df, as.character), stringsAsFactors=FALSE)
top_df$oncogene = top$hgnc_symbol
write.csv(top_df2, file="top_oncogene_intervals.csv")
```

```{r}
sink("top_oncogene_intervals.txt")
for (i in 1:nrow(top_df)){
  cat(top_df[i,"oncogene"])
  cat("\t")
  cat(unlist(top_df[i,'V1'][[1]]))
  cat("\n")
}
sink()
```

```{r}
data = data %>% mutate(query = paste(paste(gsub("chr","",chromosome),start,sep=":"),end,sep=":"))


gene_in_intervals = lapply(data$query, function(x){
  result = getBM(attributes = c("hgnc_symbol","ensembl_gene_id", "chromosome_name", "start_position", "end_position"),filters = c("chromosomal_region"),values = x, mart = ensembl)
  return(result)
})

genes_in_intervals = as.data.frame(do.call(rbind, gene_in_intervals))
```

```{r}
EGFR = lapply(data$query, function(x){
  result = getBM(attributes = c("hgnc_symbol","ensembl_gene_id", "chromosome_name", "start_position", "end_position"),filters = c("chromosomal_region"),values = x, mart = ensembl)
  if (nrow(result) > 0){
    if(!is.na(result$hgnc_symbol)){
      if(nrow(result %>% filter(hgnc_symbol == "EGFR")) > 0){
    print(x)
  }}}
  return(result)
})


```

```{r}
feq = data.frame(table(as.factor(genes_in_intervals$ensembl_gene_id))) %>% filter(Freq > 3)
colnames(feq) = c("ensembl_gene_id","Freq")
total <- unique(merge(feq,genes_in_intervals,by="ensembl_gene_id"))

total = total %>% filter(!hgnc_symbol %in% oncogenes$OncogeneName)

added_new = data.frame(matrix(0, nrow = nrow(total), ncol = length(unique(data$tissue_type))))
colnames(added_new) = unique(data$tissue_type)
total = cbind(total,added_new)
total$chromosome_name = paste("chr",total$chromosome_name,sep = "")


```

```{r}
for (j in 1:nrow(total)){
  for (i in 1:nrow(data)){
    if ((total[j,'start_position'] >= (data[i,'start'])) && (total[j,'end_position'] <= (data[i,'end'])) && 
        total[j,'chromosome_name']  == data[i,"chromosome"]){
      total[j,data[i,'tissue_type']] <-  (total[j,data[i,'tissue_type']] + 1)
    }
  }
}
```

```{r}
sum_genes = unique(total %>% mutate(sum = rowSums(total[,7:30])))
sum_genes[sum_genes == ""] <- NA
sum_genes = unique(sum_genes) %>% filter(sum >4)
sum_genes = sum_genes[ , -which(names(sum_genes) %in% c("Freq"))]

                   

```

joining oncogenes and genes
```{r}
sum_genes$gene_type = 0
sum_happened$gene_type = 1

sum_happened_frequent = sum_happened %>% filter(sum > 3)
sum_happened_frequent = sum_happened_frequent[ , -which(names(sum_happened_frequent) %in% c("length"))]

all = rbind(sum_happened_frequent,sum_genes) %>% arrange(desc(sum))
all = all[,c(1,2,3,4,5,30,31,6:29)]
```

